### ISSUE TITLE
Saving a map crashes on Android

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#107]

**Comment by andreas-eberle** [comment]
Stack trace from logcat:

```
06-15 15:28:35.415: W/System.err(7111): java.io.NotActiveException
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:366)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.movable.MovableGrid.writeObject(MovableGrid.java:57)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1053)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.GameSerializer$GameSaveTask.run(GameSerializer.java:93)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.Thread.run(Thread.java:841)
06-15 15:28:35.415: W/System.err(7111): java.io.IOException: Error saving map.
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.GameSerializer.save(GameSerializer.java:56)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.save.MapList.saveMap(MapList.java:195)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.MainGrid$GuiInputGrid.save(MainGrid.java:1629)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.input.GuiTaskExecutor.save(GuiTaskExecutor.java:159)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.input.GuiTaskExecutor.executeTask(GuiTaskExecutor.java:95)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.network.synchronic.timer.NetworkTimer.executeTasksPacket(NetworkTimer.java:168)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.network.synchronic.timer.NetworkTimer.executeRun(NetworkTimer.java:141)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.network.synchronic.timer.NetworkTimer.run(NetworkTimer.java:108)
06-15 15:28:35.415: W/System.err(7111): 	at java.util.Timer$TimerImpl.run(Timer.java:284)
06-15 15:28:35.415: W/System.err(7111): Caused by: java.io.NotActiveException
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:366)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.movable.MovableGrid.writeObject(MovableGrid.java:57)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1053)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
06-15 15:28:35.415: W/System.err(7111): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
06-15 15:28:35.415: W/System.err(7111): 	at jsettlers.logic.map.grid.GameSerializer$GameSaveTask.run(GameSerializer.java:93)
06-15 15:28:35.415: W/System.err(7111): 	at java.lang.Thread.run(Thread.java:841)
```
