### ISSUE TITLE
NullPointerException in Background causes users of IGraphicsBackgroundListener to crash

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#13]
Whenever the background is invalidated (for example on zooming), a call to Background.backgroundChangedAt(int,int) may crash due to a race condition by throwing a NullPointerException:

```
java.lang.NullPointerException
	at jsettlers.graphics.map.draw.Background.backgroundChangedAt(Background.java:1731)
	at jsettlers.logic.map.newGrid.landscape.LandscapeGrid.setLandscapeTypeAt(LandscapeGrid.java:127)
	at jsettlers.logic.map.newGrid.landscape.LandscapeGrid.flaten(LandscapeGrid.java:203)
	at jsettlers.logic.map.newGrid.landscape.LandscapeGrid.walkOn(LandscapeGrid.java:187)
	at jsettlers.logic.map.newGrid.movable.MovableGrid.movableEntered(MovableGrid.java:71)
	at jsettlers.logic.map.newGrid.MainGrid$MovablePathfinderGrid.enterPosition(MainGrid.java:1151)
	at jsettlers.logic.movable.Movable.initGoingSingleStep(Movable.java:273)
	at jsettlers.logic.movable.Movable.goSinglePathStep(Movable.java:264)
	at jsettlers.logic.movable.Movable.pathingAction(Movable.java:249)
	at jsettlers.logic.movable.Movable.timerEvent(Movable.java:214)
	at jsettlers.logic.timer.RescheduleTimer.timerEvent(RescheduleTimer.java:76)
	at jsettlers.network.synchronic.timer.ScheduledTimerable.checkExecution(ScheduledTimerable.java:35)
	at jsettlers.network.synchronic.timer.NetworkTimer.executeRun(NetworkTimer.java:142)
	at jsettlers.network.synchronic.timer.NetworkTimer.fastForward(NetworkTimer.java:220)
	at jsettlers.input.GuiInterface.action(GuiInterface.java:158)
	at jsettlers.graphics.map.MapInterfaceConnector$1.fireAction(MapInterfaceConnector.java:34)
	at jsettlers.graphics.action.ActionFirerer$ActionFirererThread.run(ActionFirerer.java:97)
```

The race condition happens between the UI thread and the thread running the central timer of the game logic.

**Comment by andreas-eberle** [comment]
@michaelzangl : Can you have a look at my fix in bc5775dcd28d8387f30d173c2706617ec1a49578. Do you see any problems with that solution? I tested it a bit and did not have any trouble.
