### ISSUE TITLE
Can not create or join Multiplayer Game in Swing

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#134]
With the current master, when I run SwingManagedJSettlers and click the Button "neues Netzwerkspiel", choose a map and click the Button "Erstellen", then I get an Exception:
<img width="1200" alt="bildschirmfoto 2015-08-16 um 08 08 59" src="https://cloud.githubusercontent.com/assets/6422616/9292282/2d913132-43ef-11e5-9d70-cf525d8fdb02.png">
```
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught IllegalArgumentException: Could not find ready.0 in image map. on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1435)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:526)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:580)
	at com.jogamp.opengl.awt.GLCanvas.update(GLCanvas.java:863)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.lwawt.LWRepaintArea.updateComponent(LWRepaintArea.java:47)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1314)
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198)
	at java.awt.Component.dispatchEventImpl(Component.java:4957)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Could not find ready.0 in image map.
	at jsettlers.common.images.TextureMap.getIndex(TextureMap.java:24)
	at jsettlers.graphics.map.draw.ImageProvider.getDirectImage(ImageProvider.java:231)
	at jsettlers.graphics.map.draw.ImageProvider.getImage(ImageProvider.java:176)
	at jsettlers.graphics.ui.UIPanel.drawBackground(UIPanel.java:130)
	at jsettlers.graphics.ui.UIPanel.drawAt(UIPanel.java:114)
	at jsettlers.graphics.ui.LabeledButton.drawAt(LabeledButton.java:54)
	at jsettlers.graphics.ui.UIPanel$ChildLink.drawAt(UIPanel.java:176)
	at jsettlers.graphics.ui.UIPanel.drawAt(UIPanel.java:120)
	at jsettlers.graphics.JSettlersScreen$PanelRegionContent.drawContent(JSettlersScreen.java:114)
	at go.graphics.region.Region.drawRegion(Region.java:109)
	at go.graphics.area.Area.drawRegionAt(Area.java:133)
	at go.graphics.area.Area.drawArea(Area.java:121)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:163)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:96)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1421)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	... 31 more
```

By the way:
When I checkout the master and start SwingManagedJSettlers I will be asked for the settlers folder.
After I entered it, the application crushes. I found out, that in the then created /config.prp the entry "resources-folder" is missing. When I add it like that the following way, it is fixed.
```
resources-folder=jsettlers.common/resources/
```
Did I something wrong with the config.prp and is that the reason for the missing index in the graphics map above?
On the other hand I did not found another resources dir, so maybe there is some graphic missing or some wrong index.

**Comment by codingberlin** [comment]
Besides the reason why I open this issue and the last one ( #129 ) is, that I need to run the network games to verify my fork "computerplayer" ( https://github.com/codingberlin/settlers-remake/tree/computerplayer ) in the network before I pull request it.

**Comment by andreas-eberle** [comment]
Hi @codingberlin: I will have a look, why the selection of the settlers folder crashed... However, your resources-folder path is slightly wrong. If you checked out the git repo as it is and start the SwingManagedJSettlers.main(), the config.prp in the folder "jsettlers.main.swing" should have the following entry:

```resources-folder=../jsettlers.common/resources/```

(Notice the `../`).

Does this help?

**Comment by codingberlin** [comment]
my settlers-remake/jsettlers.main.swing/config.prp has the content
```
#This properties are used for development

#Specifies the folder where the resources can be found. NOTE: The path needs to end with a slash ( / )
resources-folder=../jsettlers.common/resources/

#Folder containing the folders of the graphics and the sound files. If you want to specify multiple possible folders, use a ";" character for separation.
settlers-folder=/home/michael/.jsettlers;D:/Games/Siedler3;C:/Program Files/siedler 3
```

My settlers-remake/config.prp will be created by starting JSettlers after choosing the settlers3 dir with the following content:
```
#Updated settlers-folder with dialog.
#Sun Aug 16 07:36:06 CEST 2015
settlers-folder=/Users/stephanbauer/Documents/siedler3
``` 
Then the game crashes. When I modify the settlers-remake/config.prp with the following content, the game starts. ... later it crashes in the network dialog with the stack trace above.
```
#Updated settlers-folder with dialog.
#Sun Aug 16 07:36:06 CEST 2015
settlers-folder=/Users/stephanbauer/Documents/siedler3

#Specifies the folder where the resources can be found. NOTE: The path needs to end with a slash ( / )
resources-folder=jsettlers.common/resources/
``` 

So it seems so that the settlers-remake/config.prp is ignored.

But maybe this has something to do with IntelliJ which I'm using instead of Eclipse now or with something else. I have a workaround to start the game. So I guess its good to focus on the Stack Trace above which occurs at the network dialog.

Regarding the computerplayer branch ... if you like to get some information about it and if you can speak german you could take a look at my diary I wrote about the fun I had programming the branch: http://siedler3.net/cb3/topic.php?t=5628

**Comment by andreas-eberle** [comment]
I will have a look this weekend.

Regarding your diary: Great! I'm so excited to see this in action!

**Comment by michaelzangl** [comment]
> Could not find ready.0 in image map.

There is a reference to a png file missing that should be included in the build. The image map is a auto-generated and then compiled file that is included in the jar and interdependent from any other settings.

**Comment by michaelzangl** [comment]
@codingberlin Can you please open a separate bug report for the resources folder crash (if the problem still exists) and assign to Andreas Eberle?

**Comment by codingberlin** [comment]
I'm on holidays now.

I'll run the build steps when I'm back and check if the bug still exsist or just was at my machine.

Regarding the config I'll open a separate issue then, too.

**Comment by codingberlin** [comment]
I'm so sorry.
To run the ant builds fixed the issue.
