### ISSUE TITLE
Screen turns white when dragging main menu window on another screen

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#170]
There's no issue when the game is used on the screen where it has been started and the window can be resized there. Dragging the window on another (potentially bigger screen) causes the window to turn white. Dragging the window back to the original screen doesn't have any effect.

The game is randomly started on the "right" screen, i.e. randomly starts on different screens, so that I usually get it to work as I want with 5 to 20 starts.

On console I get

    $ java -jar JSettlers.jar jsettlers.main.swing.SwingManagedJSettlers --console-output --activate-all-players
    Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
    Warning: Could not load LocaleSuffix [_de_DE]. Falling back to next file.
    Loading Sequence number 28
    X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 3/3, reusable (open, marked uncloseable): 0, pending (open in creation order): 3)
    X11Util: Open X11 Display Connections: 3
    X11Util: Open[0]: NamedX11Display[:0, 0x7fa5f8005670, refCount 1, unCloseable false]
    X11Util: Open[1]: NamedX11Display[:0, 0x7fa5f801d690, refCount 1, unCloseable false]
    X11Util: Open[2]: NamedX11Display[:0, 0x7fa5fa1f7550, refCount 1, unCloseable false]

After starting the game on the original screen and dragging to another screen I get

    $ java -jar JSettlers.jar jsettlers.main.swing.SwingManagedJSettlers --console-output --activate-all-players
    Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
    Warning: Could not load LocaleSuffix [_de_DE]. Falling back to next file.
    Loading Sequence number 28
    JsettlersGame(): seed: 4711 playerId: 0 availablePlayers: [PlayerSetting(isAvailable: true, isAi: false), PlayerSetting(isAvailable: true, isAi: true), PlayerSetting(isAvailable: true, isAi: true), PlayerSetting(isAvailable: true, isAi: true)] multiplayer: false mapCreator: MapLoader: mapName: mountainlake.map mapId: 066d3c28-8f37-41cf-96c1-270109f00b9f
    First random numbers: 0.0431587286913816 0.3783154009540295 0.15090356871441724 0.30450276632169715
    Error loading building file for DONKEY_FARM:/mnt/data/data/sources/settlers-remake/target/JSettlers/resources/buildings/donkey_farm.xml (Datei oder Verzeichnis nicht gefunden)
    Building file defect: DONKEY_FARM
    WARNING: Building DONKEY_FARM does not have an image definition.
    Error loading building file for HOSPITAL:/mnt/data/data/sources/settlers-remake/target/JSettlers/resources/buildings/hospital.xml (Datei oder Verzeichnis nicht gefunden)
    Building file defect: HOSPITAL
    WARNING: Building HOSPITAL does not have an image definition.
    Error loading building file for BIG_TEMPLE:/mnt/data/data/sources/settlers-remake/target/JSettlers/resources/buildings/big_temple.xml (Datei oder Verzeichnis nicht gefunden)
    Building file defect: BIG_TEMPLE
    WARNING: Building BIG_TEMPLE does not have an image definition.
    grid filled
    Background texture generated in 47ms
    Loading Sequence number 0
    Loading Sequence number 1
    Loading Sequence number 2
    Loading Sequence number 3
    Loading Sequence number 65
    Loading Sequence number 16
    Loading Sequence number 17
    Loading Sequence number 8
    Loading Sequence number 2
    Loading Sequence number 7
    Loading Sequence number 1
    Loading Sequence number 9
    Loading Sequence number 21
    Loading Sequence number 0
    Loading Sequence number 15
    Loading Sequence number 4
    Loading Sequence number 17
    Loading Sequence number 63
    Loading Sequence number 31
    Loading Sequence number 33
    Loading Sequence number 43
    Loading Sequence number 47
    Loading Sequence number 49
    Loading Sequence number 52
    Loading Sequence number 56
    Loading Sequence number 34
    Loading Sequence number 39
    Loading Sequence number 66
    Loading Sequence number 53
    Loading Sequence number 55
    Loading Sequence number 51
    Loading Sequence number 46
    Loading Sequence number 54
    Loading Sequence number 13
    Loading Sequence number 21
    Loading Sequence number 65
    Loading Sequence number 40
    Loading Sequence number 28
    Main draw handler cought throwable:
    com.jogamp.opengl.GLException: Buffer with name 10 not tracked
	    at jogamp.opengl.GLBufferObjectTracker.mapBufferImpl(GLBufferObjectTracker.java:377)
	    at jogamp.opengl.GLBufferObjectTracker.mapBufferImpl(GLBufferObjectTracker.java:357)
	    at jogamp.opengl.GLBufferObjectTracker.mapBuffer(GLBufferObjectTracker.java:308)
	    at jogamp.opengl.gl4.GL4bcImpl.mapBuffer(GL4bcImpl.java:38816)
	    at jogamp.opengl.gl4.GL4bcImpl.glMapBuffer(GL4bcImpl.java:38812)
	    at go.graphics.swing.opengl.JOGLDrawContext.startWriteGeometry(JOGLDrawContext.java:405)
	    at jsettlers.graphics.map.draw.Background.drawMapContent(Background.java:1322)
	    at jsettlers.graphics.map.MapContent.drawBackground(MapContent.java:524)
	    at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:217)
	    at go.graphics.region.Region.drawRegion(Region.java:109)
	    at go.graphics.area.Area.drawRegionAt(Area.java:133)
	    at go.graphics.area.Area.drawArea(Area.java:121)
	    at go.graphics.swing.AreaContainer.draw(AreaContainer.java:163)
	    at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:96)
	    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	    at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1421)
	    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	    at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1435)
	    at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	    at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:526)
	    at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:580)
	    at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	    at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:73)
	    at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	    at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:592)
	    at java.awt.Component.dispatchEventImpl(Component.java:4948)
	    at java.awt.Component.dispatchEvent(Component.java:4698)
	    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	    at java.awt.EventQueue.access$300(EventQueue.java:103)
	    at java.awt.EventQueue$3.run(EventQueue.java:706)
	    at java.awt.EventQueue$3.run(EventQueue.java:704)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	    at java.awt.EventQueue$4.run(EventQueue.java:720)
	    at java.awt.EventQueue$4.run(EventQueue.java:718)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
    X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 3/3, reusable (open, marked uncloseable): 0, pending (open in creation order): 3)
    X11Util: Open X11 Display Connections: 3
    X11Util: Open[0]: NamedX11Display[:0, 0x7f03880062d0, refCount 1, unCloseable false]
    X11Util: Open[1]: NamedX11Display[:0, 0x7f038801e820, refCount 1, unCloseable false]
    X11Util: Open[2]: NamedX11Display[:0, 0x7f038a6f6c70, refCount 1, unCloseable false]

I created a video and will share it on videobin.org as soon as I have figured out the million build issues and segmentation faults of ffmpeg2theora.

experienced with v0.1.3-alpha-174-gaefd30d on Ubuntu 15.04 amd64

**Comment by michaelzangl** [comment]
You don't need that video, I can reproduce the issue.

The problem is that the GL context gets destroyed when moving between screens and we do not track that. We need to register a listener on that and then reload the graphics.

**Comment by krichter722** [comment]
This seems to be fixed in v0.1.3-alpha-303-g26bf534.

**Comment by krichter722** [comment]
This is no longer fixed in v0.1.3-alpha-491-geac312b and I can reproduce the issue in v0.1.3-alpha-303-g26bf534. This points to issues with dependencies.
