### ISSUE TITLE
Android sometimes crashes on leaving the game

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#172]
After starting a game on Android and leaving it by pressing the back button and then the "Spiel Verlassen" button, the game sometimes crashes with the following exception

```
09-26 14:21:03.977: E/AndroidRuntime(17422): FATAL EXCEPTION: main
09-26 14:21:03.977: E/AndroidRuntime(17422): Process: jsettlers.main.android, PID: 17422
09-26 14:21:03.977: E/AndroidRuntime(17422): android.content.res.Resources$NotFoundException: Unable to find resource ID #0xe245be9
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.content.res.Resources.getResourceName(Resources.java:3216)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:896)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.BackStackRecord.run(BackStackRecord.java:833)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.os.Handler.handleCallback(Handler.java:739)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.os.Handler.dispatchMessage(Handler.java:95)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.os.Looper.loop(Looper.java:145)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at android.app.ActivityThread.main(ActivityThread.java:5942)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at java.lang.reflect.Method.invoke(Native Method)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at java.lang.reflect.Method.invoke(Method.java:372)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
09-26 14:21:03.977: E/AndroidRuntime(17422):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

Test device: Samsung Galaxy S4 with Samsungs Android 5.0.1.

**Comment by DerKrawallkeks** [comment]
The problem never occurred to me. But a similar one: the game crashes when changing to another running app. (Not a problem if you save before)
Just wanted to report;) I guess that's normal

**Comment by Tom-Pratt** [comment]
probably no longer an issue since android pr
