### ISSUE TITLE
MaterialPriorityPanel broken

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#214]
Nothing happens when I press the reorder buttons in the MaterialPriorityPanel.

Pressing to "order to top" button I get:
```
Using map pos: (497|479) => [PLANK, STONE, TRUNK, IRON, IRONORE, COAL, BREAD, FISH, MEAT, FLOUR, CROP, PIG, WATER, SWORD, BOW, SPEAR, BLADE, HAMMER, AXE, PICK, SAW, FISHINGROD, SCYTHE, GOLDORE, GOLD, WINE, HONEY, MEAD]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -985
	at jsettlers.graphics.map.controls.original.panel.content.MaterialPriorityContent.reorder(MaterialPriorityContent.java:261)
	at jsettlers.graphics.map.controls.original.panel.content.MaterialPriorityContent.reorderSelected(MaterialPriorityContent.java:233)
	at jsettlers.graphics.map.controls.original.panel.content.MaterialPriorityContent.createChangeorderAction(MaterialPriorityContent.java:221)
	at jsettlers.graphics.map.controls.original.panel.content.MaterialPriorityContent$ReorderButton.getAction(MaterialPriorityContent.java:189)
	at jsettlers.graphics.ui.Button.getAction(Button.java:64)
	at jsettlers.graphics.ui.UIPanel$ChildLink.getActionRelative(UIPanel.java:187)
	at jsettlers.graphics.ui.UIPanel.getAction(UIPanel.java:225)
	at jsettlers.graphics.map.controls.original.panel.content.MaterialPriorityContent$MaterialPriorityPanel.getAction(MaterialPriorityContent.java:144)
	at jsettlers.graphics.ui.UIPanel$ChildLink.getActionRelative(UIPanel.java:187)
	at jsettlers.graphics.ui.UIPanel.getAction(UIPanel.java:225)
	at jsettlers.graphics.ui.UIPanel$ChildLink.getActionRelative(UIPanel.java:187)
	at jsettlers.graphics.ui.UIPanel.getAction(UIPanel.java:225)
	at jsettlers.graphics.ui.UIPanel$ChildLink.getActionRelative(UIPanel.java:187)
	at jsettlers.graphics.ui.UIPanel.getAction(UIPanel.java:225)
	at jsettlers.graphics.map.controls.original.OriginalControls.getActionFor(OriginalControls.java:232)
	at jsettlers.graphics.map.MapContent.getActionForCommand(MapContent.java:688)
	at jsettlers.graphics.map.MapContent.handleEvent(MapContent.java:536)
	at go.graphics.region.Region.fireGoEvent(Region.java:210)
	at go.graphics.region.Region.handleEvent(Region.java:228)
	at go.graphics.area.Area.handleCommandEvent(Area.java:367)
	at go.graphics.area.Area.handleEvent(Area.java:387)
	at go.graphics.swing.AreaContainer.handleEvent(AreaContainer.java:173)
	at go.graphics.event.interpreter.AbstractEventConverter.handleEvent(AbstractEventConverter.java:251)
	at go.graphics.event.interpreter.AbstractEventConverter.fireCommandEvent(AbstractEventConverter.java:201)
	at go.graphics.event.interpreter.AbstractEventConverter.tryReplaceEvent(AbstractEventConverter.java:293)
	at go.graphics.event.interpreter.AbstractEventConverter.endDraw(AbstractEventConverter.java:90)
	at go.graphics.swing.event.swingInterpreter.GOSwingEventConverter.mouseReleased(GOSwingEventConverter.java:156)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by michaelzangl** [comment]
Fixed in f2fde2474585ce349439015b1d6124cf9a7c3a40, not merged yet.
