### ISSUE TITLE
AI crash on original user map 512-4-Mountain_Lake

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#254]
#### Description

The AI crashs with the stack trace given below. This results in the AI doing nothing. 

I experienced the bug on the map 512-4-Mountain_Lake. To reproduce it, you simply need to start the game (I did it with --all-ai). During the first AI action, it will crash. 

#### Map-Download
https://mapbase.siedler3.net/down.php?fileid=135

#### Stack trace
```
WARNING: Networking Timer catched Throwable!!!
java.lang.NullPointerException
	at jsettlers.ai.army.WinnerGeneral.levyUnits(WinnerGeneral.java:88)
	at jsettlers.ai.highlevel.WhatToDoAi.applyRules(WhatToDoAi.java:135)
	at jsettlers.ai.highlevel.AiExecutor.timerEvent(AiExecutor.java:63)
	at jsettlers.network.synchronic.timer.ScheduledTimerable.checkExecution(ScheduledTimerable.java:49)
	at jsettlers.network.synchronic.timer.NetworkTimer.executeRun(NetworkTimer.java:157)
	at jsettlers.network.synchronic.timer.NetworkTimer.run(NetworkTimer.java:108)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
```

**Comment by codingberlin** [comment]
I'm at a business trip and will take a look at this when I'm back.
