### ISSUE TITLE
AI throws exception when an AI player has no towers left.

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#269]
Sometimes the AI throws an exception when it has no towers left.

### Stacktrace:
```
WARNING: Networking Timer catched Throwable!!!
java.lang.ArithmeticException: / by zero
	at jsettlers.ai.construction.BestMilitaryConstructionPositionFinder.calculateCenterOfPlayer(BestMilitaryConstructionPositionFinder.java:155)
	at jsettlers.ai.construction.BestMilitaryConstructionPositionFinder.findBestConstructionPosition(BestMilitaryConstructionPositionFinder.java:70)
	at jsettlers.ai.highlevel.WhatToDoAi.construct(WhatToDoAi.java:370)
	at jsettlers.ai.highlevel.WhatToDoAi.buildTower(WhatToDoAi.java:326)
	at jsettlers.ai.highlevel.WhatToDoAi.buildBuildings(WhatToDoAi.java:227)
	at jsettlers.ai.highlevel.WhatToDoAi.applyRules(WhatToDoAi.java:138)
	at jsettlers.ai.highlevel.AiExecutor.timerEvent(AiExecutor.java:64)
	at jsettlers.network.synchronic.timer.ScheduledTimerable.checkExecution(ScheduledTimerable.java:49)
	at jsettlers.network.synchronic.timer.NetworkTimer.executeRun(NetworkTimer.java:157)
	at jsettlers.network.synchronic.timer.NetworkTimer.run(NetworkTimer.java:108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by codingberlin** [comment]
This was fixed with the last release
