### ISSUE TITLE
GUI disappears on game start

### ISSUE THREAD

**Issue by iandioch** [jsettlers/settlers-remake#310]
I tried to start the game, using both assets from the Amazons demo, and also from a physical CD, and both times the following happened:
- I started the JAR
- The menu showed ok, with the button assets showing fine
- I started a new single player game with several different maps, it didn't seem to make a difference
- When the game loaded, it would display fine for a split second
- The left menu would disappear, and all of the entities on the screen would disappear, leaving just the map
- The game would still run - I could hear the sound effects, and the people still left footprints. Image [here](http://i.imgur.com/99p0CjM.jpg)

**Comment by andreas-eberle** [comment]
Hi @iandioch,

can you send me the logfiles? They are in the folder `resources/logs`. (andreas.eberle [at] settlers-android-clone.com)

Best regards

**Comment by iandioch** [comment]
Sorry for the delayed response. I didn't know the logs there existed. The relevant part of the log is below.

```
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Could not find/load graphic file 13
Main draw handler cought throwable:
java.lang.ArithmeticException: / by zero
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawPlayerableWaving(MapObjectDrawer.java:1042)
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawMapObject(MapObjectDrawer.java:298)
	at jsettlers.graphics.map.MapContent.drawTile(MapContent.java:433)
	at jsettlers.graphics.map.MapContent.drawMain(MapContent.java:403)
	at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:220)
	at go.graphics.region.Region.drawRegion(Region.java:109)
	at go.graphics.area.Area.drawRegionAt(Area.java:133)
	at go.graphics.area.Area.drawArea(Area.java:121)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:163)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:96)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1421)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1435)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:526)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:580)
	at com.jogamp.opengl.awt.GLCanvas.update(GLCanvas.java:863)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:51)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
	at java.awt.Component.dispatchEventImpl(Component.java:4967)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

As it said I was missing graphic file 13, I looked into the Gfx folder, and saw that I indeed had a file `Siedler3_13.f8007e01f.dat`. However, most of the other files started with a lowercase `s`. I renamed the file to match, and the game played fine.

Sorry for the bother! Looking now, the assets from my physical CD are named `S3_00.DAT`, compared to the ones from the Amazons demo `siedler3_00.f8007e01f.dat` (some starting with a capital s). It might be nice for the game to recognise assets named in a different format?

**Comment by andreas-eberle** [comment]
Hi @iandioch,

thanks for your answer and your investigation. Of course, the game should be able to handle upper case file names. 

@michaelzangl: Can you implement this?

Best regards

**Comment by iandioch** [comment]
@andreas-eberle I would love to do this fix myself if you give me some time to get acquainted with the codebase.

**Comment by andreas-eberle** [comment]
@iandioch: Feel free to do so. I'm looking for your PR. If you have some questions, feel free to ask. As I cannot assign you, I cleared the assignee for now.

**Comment by michaelzangl** [comment]
@iandioch Which version of the settlers files are you using?

**Comment by iandioch** [comment]
Sorry for the lack of response on this. If you can go ahead with it, do it; I won't have any free time in the near future.

I was using assets from a physical copy of the game. The number it references on the disc and on the sleeve is `ESS373/D`, if that means anything. It's an Ubisoft 2 CD version, as was the norm 15 years ago :)

**Comment by andreas-eberle** [comment]
Already fixed in referenced PR.
