### ISSUE TITLE
MapCreator.jar - save map problem

### ISSUE THREAD

**Issue by justangel** [jsettlers/settlers-remake#34]
after created a map, set up the basic resources, put players Spawn points, then press "SAVE" and nothing happens.
When you click on "PLAY", the map editor does not respond

OS: win8.1x64

C:\WINDOWS\system32>java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

MapCreator.jar last version from master

**Comment by namelessjames** [comment]
For debugging reason, try to start JSettlers.jar with the admin command and then post any error messages output in the console window here:
``` java -jar JSettlers.jar --console-output ```

**Comment by justangel** [comment]
maybe you mean
java -jar MapCreator.jar --console-output

when press "SAVE" error in console:

Calculating partitions needed: 1 ms
found 4 partitions.
java.lang.UnsupportedOperationException
        at jsettlers.logic.map.save.DirectoryMapLister.getOutputStream(Directory
MapLister.java:93)
        at jsettlers.logic.map.save.MapList.saveNewMap(MapList.java:150)
        at jsettlers.mapcreator.main.EditorWindow.save(EditorWindow.java:565)
        at jsettlers.mapcreator.main.EditorWindow$2.actionPerformed(EditorWindow
.java:447)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
18)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonL
istener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:713)
        at java.awt.EventQueue$4.run(EventQueue.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by justangel** [comment]
java -jar MapCreator.jar --console-output

When click on "PLAY" button, the map editor does not respond for a while, depending on map size

Starting process:
java -classpath MapCreator.jar jsettlers.main.swing.SwingManagedJSettlers --mapf
ile=C:\Users\JUST_T~1\AppData\Local\Temp\tmp_map2151149639393529263
Current working dir: G:\games\JSettlers\..\jsettlers.main.swing
java.io.IOException: Cannot run program "java" (in directory "G:\games\JSettlers
\..\jsettlers.main.swing"): CreateProcess error=267, ??????? ?????? ??? ?????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at jsettlers.mapcreator.main.EditorWindow.play(EditorWindow.java:602)
        at jsettlers.mapcreator.main.EditorWindow$9.actionPerformed(EditorWindow
.java:524)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
18)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonL
istener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:713)
        at java.awt.EventQueue$4.run(EventQueue.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: CreateProcess error=267, ??????? ?????? ??? ????
?
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 38 more

but i found tmp_map#################### in User Temp directory, copy it to resources\maps and play it ok

**Comment by michaelzangl** [comment]
There are 2 problems (bugs) here:
(1) You cannot save the map. The packed map editor uses the same logic as the game to determine which directory to use.  The maps directory is not writable by the game, so it is forbidden to save maps there.
(2) The settlers app cannot be started, because it is not found by the map editor. It currently only looks for the app in a normal dev environment. I created a new bug for this.

Until those bugs are fixed, you can only use the copy-trick or you need to install the complete dev environment (including Eclipse) and run the map editor from there.
