### ISSUE TITLE
Settlers crashes on loading orignal maps

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#439]
**I received the following message via the [settlers remake website](www.settlers-android-clone.com)**

Tried to compile and run it via gradlew on Windows 7 64bit (+Java 8 64bit). Checked out a clone via GIT, set up development environment (Android Studio / Eclipse), configured PATH, JAVA_HOME and ANDROID_HOME accordingly … Swing builds fine … thought i was lucky and had the goal achieved … however this is what happens when i run “gradlew run”, i get:

```
:jsettlers.main.swing:run
No default command line options file found.
Options loaded: {}
Source: (file:/C:/Users/XYZ/Documents/Projekte/Java/jsettlers/jsettlers.main.swing/build/classes/main/ )
java.lang.ArrayIndexOutOfBoundsException: 232
at jsettlers.graphics.reader.AdvancedDatFileReader.getSettlerPointers(AdvancedDatFileReader.java:614)
at jsettlers.graphics.image.MultiImageMap.addSequences(MultiImageMap.java:104)
at jsettlers.graphics.reader.AdvancedDatFileReader.generateImageMap(AdvancedDatFileReader.java:646)
at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:121)
at java.lang.Thread.run(Thread.java:745)
Exception in thread “main” java.lang.ExceptionInInitializerError
at jsettlers.main.swing.lookandfeel.JSettlersLookAndFeel.install(JSettlersLookAndFeel.java:69)
at jsettlers.main.swing.SwingManagedJSettlers.createJSettlersFrame(SwingManagedJSettlers.java:209)
at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:65)
Caused by: java.awt.image.RasterFormatException: (x + width) is outside raster
at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
at jsettlers.main.swing.lookandfeel.ui.SettlersLabelUi.(SettlersLabelUi.java:61)
at jsettlers.main.swing.lookandfeel.factory.LabelUiFactory.(LabelUiFactory.java:40)
… 3 more
:jsettlers.main.swing:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ‘:jsettlers.main.swing:run’.
> Process ‘command ‘C:\Program Files\Java\jdk1.8.0_91\bin\java.exe” finished wi
th non-zero exit value 1

* Try:
Run with –stacktrace option to get the stack trace. Run with –info or –debug
option to get more log output.

BUILD FAILED

Total time: 5.541 secs
```

Strange thing though, it started once and i was able to choose the original Settlers3 Folder … however it instantly crashed afterwards … and now i cannot restart the game any longer. "git status" does not show any changed files in my local repository. Where do you store the selection of the Settlers3 folder, i've made?

**Comment by andreas-eberle** [comment]
@codingberlin @tomsoftware: Do you have an idea what could cause this?

**Comment by eLBart0-DTG** [comment]
It was me who posted that issue to your blog. However, the solution to this problem is kinda trivial: It turned out my Settlers3 Installation was corrupted. Once i've installed it again from my ancient original CD-Rom JSettlers was able to load successfully. The only reason for this ticket to stay open might be the fact that catching the exception and throwing a more meaningful exception in the future may profit the end-user to spot this problem more easy. For the final release i would definitely recommend to implement a crc32 (or whatever) hashsum check on the original Settlers3 files ... this way you can easily ensure a nice experience for the gamers, i guess :) You could then easily tell the gamers which files they are missing, which are corrupted and need to be replaced, etc. For now i'm totally aware you have completly different priorities ... so maybe you can move this idea to the backlog or something ;)

**Comment by andreas-eberle** [comment]
@eLBart0-DTG: Thanks for your reply. I changed the topic of this issue.

**Comment by tomsoftware** [comment]
if the option 
disable-original-maps-checksum = true
in config [options.prp] is not disabled (by default) the original-map loaded will (hopefully) stop loading if the map-file is corrupted so I don't know where this errer come from.

**Comment by Gordakan** [comment]
Hey ! I'm trying to run the game in swing but I got a very similar error message : 

> Found default command line options file. Starting to read.
> Default command line options file successfully read.
> Options loaded: {}
> Source: (file:/C:/Users/Gordak/Documents/PROGRAMMATION/SETTLERS/settlers-remake/jsettlers.main.swing/build/classes/main/ <no signer certificates>)
> java.lang.ArrayIndexOutOfBoundsException: 232
>         at jsettlers.graphics.reader.AdvancedDatFileReader.getSettlerPointers(AdvancedDatFileReader.java:614)
>         at jsettlers.graphics.image.MultiImageMap.addSequences(MultiImageMap.java:104)
>         at jsettlers.graphics.reader.AdvancedDatFileReader.generateImageMap(AdvancedDatFileReader.java:646)
>         at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:121)
>         at java.lang.Thread.run(Thread.java:748)
> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at jsettlers.main.swing.lookandfeel.JSettlersLookAndFeel.install(JSettlersLookAndFeel.java:69)
>         at jsettlers.main.swing.SwingManagedJSettlers.createJSettlersFrame(SwingManagedJSettlers.java:204)
>         at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:65)
> Caused by: java.awt.image.RasterFormatException: (x + width) is outside raster
>         at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
>         at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
>         at jsettlers.main.swing.lookandfeel.ui.SettlersLabelUi.<init>(SettlersLabelUi.java:61)
>         at jsettlers.main.swing.lookandfeel.factory.LabelUiFactory.<clinit>(LabelUiFactory.java:40)
>         ... 3 more
> :jsettlers.main.swing:run FAILED

It happened while trying to read file _Settlers3\gfx\siedler3_11.f8007e01f.dat_.

Has anyone a hash to share to verify integrity of gfx and snd files ?
