### ISSUE TITLE
JSettlers won't start

### ISSUE THREAD

**Issue by AlexEndris** [jsettlers/settlers-remake#487]
Hi there,
I've been wanting to give this a try for a long time, but unfortunately after the dialog to choose the original's assets, nothing happens. Starting it again, the same thing. The only thing I notice is in Task Manager "jawaw.exe" maxing one core until the memory reaches around 300 MB. After that, it just sits there and nothing happens.
Map Creator, however, works without a problem. There is sound, there are maps, there are assets.

Windows 10
Java 8 Update 90

If you need more, just tell me and I'll supply the needed information :)

**Comment by michaelzangl** [comment]
Can you try starting jsettlers from the command line? An error message should appear there somewhere.

You should be able to do this by opening a command prompt and then entering:
```
java -jar C:\...\JSettlers.jar
```

**Comment by AlexEndris** [comment]
There you go: 
`Warning: Could not load LocaleSuffix [locale=en_GB, useCountry=true]. Falling back to next file.
Checksum of original map (Gutes Leben.map) is not valid!
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at jsettlers.main.swing.JSettlersSwingUtil.createBufferedImageFrom(JSettlersSwingUtil.java:34)
        at jsettlers.main.swing.menu.openpanel.MapListCellRenderer.getPreviewIcon(MapListCellRenderer.java:189)
        at jsettlers.main.swing.menu.openpanel.MapListCellRenderer.getListCellRendererComponent(MapListCellRenderer.java:222)
        at jsettlers.main.swing.menu.openpanel.MapListCellRenderer.getListCellRendererComponent(MapListCellRenderer.java:51)
        at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
        at javax.swing.JList.setSelectedIndex(Unknown Source)
        at jsettlers.main.swing.menu.openpanel.OpenPanel.<init>(OpenPanel.java:165)
        at jsettlers.main.swing.menu.openpanel.OpenPanel.<init>(OpenPanel.java:101)
        at jsettlers.main.swing.menu.mainmenu.MainMenuPanel.<init>(MainMenuPanel.java:79)
        at jsettlers.main.swing.JSettlersFrame.<init>(JSettlersFrame.java:75)
        at jsettlers.main.swing.SwingManagedJSettlers.createJSettlersFrame(SwingManagedJSettlers.java:210)
        at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:65)`

Seeing this.. can it be that I limited the Memory somehere in the Java settings? Having had a quick look, I couldn't find anything. It's most definitely not the hardware with 32GB ;).

**Comment by codingberlin** [comment]
A theses: You have a huge amount of original maps which consumes the memory.
If it is so we have to fine a way to deal with huge amount of maps without causing OOMs.

How many maps do you have?

**Comment by AlexEndris** [comment]
Thesis seems to hold true. As I've played it a lot through a VM running XP quite some maps were downloaded. The map folder in the S3 folder is about 2 gb. (around 600 in the User folder)

Perhaps it's possible to not load all maps immediately but only a portion (pagination maybe) when they are actually needed? I don't think this would have a lot of relevancy on Android, but on Windows I could see people downloading some. At least the MapCreator can already deal with it. I didn't count, but most seem to be displayed there, if not all.

**Comment by AlexEndris** [comment]
Moved a few maps out of the folder and now it works. Still I think it would help if more maps would be supported.
Do you know how many I could add that won't end up in a OOM?

**Comment by michaelzangl** [comment]
This depends on how much memory you give to JSettlers.

You can start it from the command line using:
```
java -Xmx2G -jar JSettlers,jar
```

**Comment by AlexEndris** [comment]
I already tried that, still only used to 280MB and never showed the window. But I can try again.
