### ISSUE TITLE
Support upper/lower case file names for graphics.

### ISSUE THREAD

**Issue by TPolzer** [jsettlers/settlers-remake#489]
Under Linux several things are not rendered (hidden?):
![broken settlers rendering](http://bulsa.faui2k11.de/settlers.jpg)
This is the corresponding log:

```
$ java -jar JSettlers.jar 
No default command line options file found.
Options loaded: {}
Source: (file:/***/JSettlers.jar <no signer certificates>)
Could not find/load graphic file 01
Could not find/load graphic file 11
java.lang.NullPointerException
    at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:121)
    at java.lang.Thread.run(Thread.java:745)
Could not find/load graphic file 12
java.lang.NullPointerException
    at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:189)
    at java.lang.Thread.run(Thread.java:745)
Could not find/load graphic file 03
Could not find/load graphic file 03
Warning: Could not load LocaleSuffix [locale=en_US, useCountry=true]. Falling back to next file.
Loading Sequence number 17
Loading Sequence number 18
```

Under Windows, with the same data files, it works fine.

**Comment by michaelzangl** [comment]
That is odd. Somehow the files 11 and 12 are not found.
```
java.lang.NullPointerException
    at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:121)
```

**Comment by TPolzer** [comment]
Got it: It's #11 again.
Here is a listing of the Gfx folder (unzipped from s3amazonen_demo.exe):
```
$ ls Gfx/
siedler3_00.f8007e01f.dat  Siedler3_06.f8007e01f.dat  Siedler3_12.f8007e01f.dat  Siedler3_40.f8007e01f.dat  Siedler3_46.f8007e01f.dat  siedler3_81.f8007e01f.dat
Siedler3_01.f8007e01f.dat  Siedler3_07.f8007e01f.dat  Siedler3_13.f8007e01f.dat  Siedler3_41.f8007e01f.dat  Siedler3_47.f8007e01f.dat  siedler3_82.f8007e01f.dat
siedler3_02.f8007e01f.dat  Siedler3_08.f8007e01f.dat  Siedler3_14.f8007e01f.dat  Siedler3_42.f8007e01f.dat  Siedler3_48.f8007e01f.dat  siedler3_83.f8007e01f.dat
Siedler3_03.f8007e01f.dat  Siedler3_09.f8007e01f.dat  Siedler3_15.f8007e01f.dat  Siedler3_43.f8007e01f.dat  siedler3_70.f8007e01f.dat  siedler3_84.f8007e01f.dat
siedler3_04.f8007e01f.dat  siedler3_10.f8007e01f.dat  siedler3_16.f8007e01f.dat  Siedler3_44.f8007e01f.dat  siedler3_71.f8007e01f.dat  siedler3_85.f8007e01f.dat
siedler3_05.f8007e01f.dat  Siedler3_11.f8007e01f.dat  siedler3_17.f8007e01f.dat  Siedler3_45.f8007e01f.dat  siedler3_80.f8007e01f.dat  siedler3_99.f8007e01f.dat
```
Moving all filenames to their lowercase equivalent solves the problem.

**Comment by michaelzangl** [comment]
Thanks for reporting. I had the files of the Amazon demo once and they worked fine, so I assume that there may be different versions. We need to work around this...

**Comment by tonihele** [comment]
Here, we have the same problem:
https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/tools/convert/ConversionUtils.java#L455
