### ISSUE TITLE
Cannot load Ultimate Collection/Gold Edition in Eclipse

### ISSUE THREAD

**Issue by abledbody** [jsettlers/settlers-remake#501]
After struggling with Eclipse's project importing... Thing... I finally got the program to run, only for it to crash after loading up the GFX and SND. Any time it loads the menu it produces an error and crashes.

```
Found default command line options file. Starting to read.
Default command line options file successfully read.
Options loaded: {}
Warning: Could not load LocaleSuffix [locale=en, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=en_US, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=en_US, useCountry=true]. Falling back to next file.
C:\GOG Games\Settlers 3 Ultimate
Source: (file:/C:/Users/drewi/Java/settlers-remake-master/bin/ <no signer certificates>)
Exception in thread "image preloader" java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:78)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
    at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.readFromFile(SettlerImageMap.java:98)
    at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.readFromFile(SettlerImageMap.java:94)
    at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.<init>(SettlerImageMap.java:75)
    at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.getInstance(SettlerImageMap.java:361)
    at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:22)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.ExceptionInInitializerError
    at jsettlers.main.swing.lookandfeel.JSettlersLookAndFeel.install(JSettlersLookAndFeel.java:66)
    at jsettlers.main.swing.SwingManagedJSettlers.createJSettlersFrame(SwingManagedJSettlers.java:209)
    at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:65)
Caused by: java.lang.NullPointerException
    at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
    at jsettlers.main.swing.lookandfeel.ui.img.UiImageLoader.get(UiImageLoader.java:55)
    at jsettlers.main.swing.lookandfeel.ui.ButtonUiStone.<init>(ButtonUiStone.java:46)
    at jsettlers.main.swing.lookandfeel.factory.ButtonUiFactory.<clinit>(ButtonUiFactory.java:40)
    ... 3 more
```

I have tried all manner of naming and file location schemes, as well as a different edition of S3, but none of them work.
I've gotten it to work in Eclipse before, but not as of recently. I've also tested the nightly build, but for some reason that's just fine.

**Comment by andreas-eberle** [comment]
@michaelzangl: Do you have any ideas what could be causing this?

**Comment by michaelzangl** [comment]
No, I don't.

**Comment by abledbody** [comment]
Update on this: I just tried the map editor as well, and it's also throwing an exception.
```
No default command line options file found.
Options loaded: {}
Source: (file:/C:/Users/drewi/Java/settlers-remake-master/bin/ <no signer certificates>)
Unhandled error in Thread image preloader
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.readFromFile(SettlerImageMap.java:98)
	at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.readFromFile(SettlerImageMap.java:94)
	at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.<init>(SettlerImageMap.java:75)
	at jsettlers.graphics.map.draw.settlerimages.SettlerImageMap.getInstance(SettlerImageMap.java:361)
	at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:22)
	at java.lang.Thread.run(Thread.java:745)
Warning: Could not load LocaleSuffix [locale=en, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=en_US, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=en_US, useCountry=true]. Falling back to next file.
Unhandled error in Thread main
java.lang.ExceptionInInitializerError
	at jsettlers.mapcreator.main.MapCreatorApp.startWithSelectionDialog(MapCreatorApp.java:62)
	at jsettlers.mapcreator.main.MapCreatorApp.main(MapCreatorApp.java:110)
Caused by: java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at jsettlers.mapcreator.main.window.EditorFrame.<clinit>(EditorFrame.java:95)
	... 2 more
```

**Comment by andreas-eberle** [comment]
Can you try this with the branch of PR #495? I have some hopes that it should work there. However, the project structure changed a bit... I have no idea what this will do to your Eclipse setup. In general, we cannot really support Eclipse, as nobody of us maintainers is using it. Since Android Studio is based on IntelliJ, we're all using IntelliJ and Android Studio. However, if you find out what needs to be done to get it properly working in Eclipse, I'd be happy to put your manual in the wiki.

**Comment by andreas-eberle** [comment]
Closing this because of missing response. If this issue still persists, please reopen.
