### ISSUE TITLE
Black screen game

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#562]
For some reason only the sound starts on any version, nightly or stable, on Win 10, and generates huge logs in just seconds. This one was from just 4-5 secs

[2017-04-23_14-12-18_M256-2-Quick.zip](https://github.com/jsettlers/settlers-remake/files/949644/2017-04-23_14-12-18_M256-2-Quick.zip)

**Comment by andreas-eberle** [comment]
I had a look at the logfile and it seems that the graphics code cannot find the graphics files. @michaelzangl: Do you know what could cause the exception below (the log is spammed with this exception): 

```
go.graphics.IllegalBufferException: The texture JOGLTextureHandle [index=2] is not valid.
	at jsettlers.graphics.map.draw.DrawBuffer$Buffer.setForTexture(DrawBuffer.java:73)
	at jsettlers.graphics.map.draw.DrawBuffer.getBuffer(DrawBuffer.java:196)
	at jsettlers.graphics.map.draw.DrawBuffer.addImage(DrawBuffer.java:169)
	at jsettlers.graphics.image.SingleImage.drawAt(SingleImage.java:324)
	at jsettlers.graphics.image.SettlerImage.drawAt(SettlerImage.java:98)
	at jsettlers.graphics.map.draw.MapObjectDrawer.draw(MapObjectDrawer.java:1099)
	at jsettlers.graphics.map.draw.MapObjectDrawer.draw(MapObjectDrawer.java:1091)
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawWaves(MapObjectDrawer.java:663)
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawObject(MapObjectDrawer.java:250)
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawMapObject(MapObjectDrawer.java:191)
	at jsettlers.graphics.map.MapContent.drawTile(MapContent.java:503)
	at jsettlers.graphics.map.MapContent.drawMain(MapContent.java:472)
	at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:278)
	at go.graphics.region.Region.drawRegion(Region.java:109)
	at go.graphics.area.Area.drawRegionAt(Area.java:132)
	at go.graphics.area.Area.drawArea(Area.java:120)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:165)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:97)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:559)
	at sun.awt.RepaintArea.paintComponent(Unknown Source)
	at sun.awt.RepaintArea.paint(Unknown Source)
	at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by derfuhrer2007** [comment]
I tried with both the demo and the GOG version.

I selected installation folder I think the way it should be, where the arrow suggested. Could that be it?

**Comment by DerKrawallkeks** [comment]
I had the problem also, after initial installation. My problem was solved when I created a new folder for the gnd/snd which I called JSettlersx instead of JSettlers. Then I reinstalled. Then app will not automatically find the files, and you can manually select the right folder.

**Comment by derfuhrer2007** [comment]
Just did that to no avail,I modified my old settlers folder so that the game will ask again for it, them copied the gfx and snd folder there, selected it, but same. Is that what you did as well? 

    On Wednesday, April 26, 2017 2:06 PM, DerKrawallkeks <notifications@github.com> wrote:
 

 I had the problem also, after initial installation. My problem was solved when I created a new folder for the gnd/snd which I called JSettlersx instead of JSettlers. Then I reinstalled. Then app will not automatically find the files, and you can manually select the right folder.—

**Comment by DerKrawallkeks** [comment]
Mmh then I cannot help. This workarround did it for me, sorry

**Comment by derfuhrer2007** [comment]
Can somebody please just upload those folders here? GFX and SND?

**Comment by michaelzangl** [comment]
No (copyright issues)

**Comment by andreas-eberle** [comment]
@derfuhrer2007: I think the mentioned PR of @rpolzer should have fixed it. Please reopen if the problem still exists.
