### ISSUE TITLE
Map editor crashes after placing some spots of fish

### ISSUE THREAD

**Issue by benhandschuh** [jsettlers/settlers-remake#618]
After i place a few spots of fish into water my map editor crashes. Take a look at the error log:

```
Unhandled error in Thread AWT-EventQueue-0
---
== Thread ==
name: AWT-EventQueue-0
ID: 17
---
== Exception ==
class: java.lang.OutOfMemoryError
message: GC overhead limit exceeded
message: GC overhead limit exceeded
stacktrace:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at jsettlers.mapcreator.data.MapDataDelta.changeResource(MapDataDelta.java:110)
	at jsettlers.mapcreator.data.MapData.apply(MapData.java:523)
	at jsettlers.mapcreator.control.UndoRedoHandler.undo(UndoRedoHandler.java:81)
	at jsettlers.mapcreator.control.EditorControl$15.actionPerformed(EditorControl.java:529)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
```

**Comment by michaelzangl** [comment]
This is caused by the undo/redo queue storing the old map states. The undo queue simply takes up too much memory - or you gave the map editor to few memory on startup.
