### ISSUE TITLE
(Android) Every version newer than 59d913f crashs on entering the 3rd building tab

### ISSUE THREAD

**Issue by BlankFX1** [jsettlers/settlers-remake#666]
Every version newer than 59d913f crashs on entering the 3rd building  #tab (militairy buildings) on Android.
I haven't tested the windows build.
My device gives me the following error log:

` java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$Adapter android.support.v7.widget.RecyclerView.getAdapter()' on a null object reference
	at jsettlers.main.android.gameplay.ui.fragments.menus.buildings.BuildingsCategoryFragment.setBuildings(BuildingsCategoryFragment.java:89)
	at jsettlers.main.android.gameplay.ui.fragments.menus.buildings.BuildingsCategoryFragment_.access$001(BuildingsCategoryFragment_.java:25)
	at jsettlers.main.android.gameplay.ui.fragments.menus.buildings.BuildingsCategoryFragment_$1.run(BuildingsCategoryFragment_.java:101)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
   `
Has something been changed regarding this building tab after the above mentioned version?
Running the game on Android 5.0.1.

**Comment by tom-pratt** [comment]
@BlankFX1  That's weird, it seems ok for me. Do you get the same crash on more than one device?

**Comment by BlankFX1** [comment]
I found the above mentioned issue on my Xiaomi Redmi Note 2 but also just verified it on my partners Samsung K-Zoom, running Android 4.4.2.
Sadly the K-Zoom gave me no further Log.

However, 59d913f is running fine on both devices.

**Comment by BlankFX1** [comment]
I also tested this on Android-x86 7.1 on a real laptop and can verify this issue once again.

**Comment by tom-pratt** [comment]
Thanks for this, now fixed in #670 

Really weird that my phone wasnt crashing! Was able to debug it on the emulator though
