### ISSUE TITLE
[MapCreator] Can't create new-map, neither open any.

### ISSUE THREAD

**Issue by ethMidst** [jsettlers/settlers-remake#741]
Hello,

I tried Java10 and Java8 on LinuxMint19 - no-results.

AFAIK it's conflict between runtime and compiler: "NoClassDefFoundError: usually mismatch between compile-time and run-time"...
...If only i'd had ArchLinux still installed - I assume it'd run fine from git AUR package.

Would appreciate answer - 'cause I am stuck on Mint19 for now...

```
Unhandled error in Thread main
---
== Thread ==
name: main
ID: 1
---
== Exception ==
class: java.lang.NoClassDefFoundError
message: javax/xml/bind/JAXBContext
message: javax/xml/bind/JAXBContext
stacktrace:
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at jsettlers.mapcreator.presetloader.PresetLoader.load(PresetLoader.java:80)
	at jsettlers.mapcreator.main.window.sidebar.ToolSidebar.loadPresets(ToolSidebar.java:307)
	at jsettlers.mapcreator.main.window.sidebar.ToolSidebar.<init>(ToolSidebar.java:276)
	at jsettlers.mapcreator.control.EditorControl$1.<init>(EditorControl.java:140)
	at jsettlers.mapcreator.control.EditorControl.<init>(EditorControl.java:140)
	at jsettlers.mapcreator.main.MapCreatorApp.startWithSelectionDialog(MapCreatorApp.java:91)
	at jsettlers.mapcreator.main.MapCreatorApp.main(MapCreatorApp.java:110)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 7 more
```

**Comment by andreas-eberle** [comment]
@ethMidst: Sorry, for the late response. Did you get it fixed?
