### ISSUE TITLE
Client can't connect to default server

### ISSUE THREAD

**Issue by subesokun** [jsettlers/settlers-remake#757]
When starting the desktop client following error gets thrown. It seems like the client can't connect to the hard-coded default server.

```
jsettlers.network.infrastructure.channel.socket.SocketConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:37)
	at jsettlers.network.infrastructure.channel.Channel.<init>(Channel.java:80)
	at jsettlers.network.infrastructure.channel.AsyncChannel.<init>(AsyncChannel.java:35)
	at jsettlers.network.client.NetworkClient.<init>(NetworkClient.java:81)
	at jsettlers.main.AsyncNetworkClientConnector$1.run(AsyncNetworkClientConnector.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:35)
	... 4 more
```

Furthermore, when trying to start a network game following subsequent error gets thrown

```
jsettlers.network.infrastructure.channel.socket.SocketConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:37)
	at jsettlers.network.infrastructure.channel.Channel.<init>(Channel.java:80)
	at jsettlers.network.infrastructure.channel.AsyncChannel.<init>(AsyncChannel.java:35)
	at jsettlers.network.client.NetworkClient.<init>(NetworkClient.java:81)
	at jsettlers.main.AsyncNetworkClientConnector$1.run(AsyncNetworkClientConnector.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:35)
	... 4 more
Exception in thread "openNewGameThread" java.lang.NullPointerException
	at jsettlers.main.MultiplayerGame$2.run(MultiplayerGame.java:89)
```

OS: Ubuntu like but error happens also on Windows 10
JRE: Java(TM) SE Runtime Environment (build 1.8.0_192-b12) (Oracle)
Commit: b51b35a5c5cea8feffb5d887b0b9330769b08cd1 (latest master)

**Comment by homoroselaps** [comment]
Hej everyone,
I get the same error running the current master of jSettlers from within AndroidStudio. 
When I start a new NetworkGame I can reproduce the error from above.
OS: macOS Catalina
JRE: 1.8 I guess?


```
> Task :jsettlers.main.swing:SwingManagedJSettlers.main()
Source: (file:/Users/jt/projects/settlers-remake/jsettlers.main.swing/build/classes/java/main/ <no signer certificates>)
Warning: Could not load LocaleSuffix [locale=en_DE, useCountry=true]. Falling back to next file.
Could not load LocaleSuffix [locale=en_DE, useCountry=true]. Falling back to next file.

jsettlers.network.infrastructure.channel.socket.SocketConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:37)
	at jsettlers.network.infrastructure.channel.Channel.<init>(Channel.java:80)
	at jsettlers.network.infrastructure.channel.AsyncChannel.<init>(AsyncChannel.java:35)
	at jsettlers.network.client.NetworkClient.<init>(NetworkClient.java:81)
	at jsettlers.main.AsyncNetworkClientConnector$1.run(AsyncNetworkClientConnector.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
Caused by: java.net.ConnectException: Connection refused (Connection refused)

	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:35)
	... 4 more
jsettlers.network.infrastructure.channel.socket.SocketConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:37)
	at jsettlers.network.infrastructure.channel.Channel.<init>(Channel.java:80)
	at jsettlers.network.infrastructure.channel.AsyncChannel.<init>(AsyncChannel.java:35)
	at jsettlers.network.client.NetworkClient.<init>(NetworkClient.java:81)
	at jsettlers.main.AsyncNetworkClientConnector$1.run(AsyncNetworkClientConnector.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:35)
	... 4 more
Exception in thread "openNewGameThread" java.lang.NullPointerException
	at jsettlers.main.MultiplayerGame$2.run(MultiplayerGame.java:89)

```

**Comment by paulwedeck** [comment]
JSettlers-master does not run well with java9+
Andreas is no longer hosting the default server. That means that you locally host a server and set the server option to the host's ip
