### ISSUE TITLE
SettlersDirectoryException on Mac OS X

### ISSUE THREAD

**Issue by jeancdc** [jsettlers/settlers-remake#76]
Hi,

I can't execute the JSettlers.jar. I've got the following message:
```
Exception in thread "main" SettlersDirectoryException [expectedSnds=[/Users/jeancreuzedeschatelliers/JSettlers/Siedler3/SND, /Users/jeancreuzedeschatelliers/JSettlers/Siedler3/snd, /Users/jeancreuzedeschatelliers/JSettlers/Siedler3/Snd], expectedGfxs=[/Users/jeancreuzedeschatelliers/JSettlers/Siedler3/GFX, /Users/jeancreuzedeschatelliers/JSettlers/Siedler3/gfx, /Users/jeancreuzedeschatelliers/JSettlers/Siedler3/Gfx], badVersion=true]
	at jsettlers.graphics.swing.resources.SwingResourceLoader.testConfig(SwingResourceLoader.java:61)
	at jsettlers.graphics.swing.resources.SwingResourceLoader.setupGraphicsAndSoundResources(SwingResourceLoader.java:25)
	at jsettlers.main.swing.SwingManagedJSettlers.setupResourceManagers(SwingManagedJSettlers.java:117)
	at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:58)
```

I'm under Mac OS X 10.10 Yosemite. My version of Java is 1.8.0_25-b17.

I've installed the original game with Wine.

Could you see ? Thanks.

**Comment by justangel** [comment]
in your dir /Users/jeancreuzedeschatelliers/JSettlers/Siedler3
you needed to put folders SND and GFX from original game, eg gold edition ver.1.60

**Comment by jeancdc** [comment]
Yes, they are already in this folder...

**Comment by jeancdc** [comment]
OK, I installed the game on a PC, updated it to version 1.60 and copy the Gfx and Sfx folders from my installed dir into my /Users/jeancreuzedeschatelliers/JSettlers/Siedler3 dir. And it works!
