### ISSUE TITLE
Grafics files have different naming in Amazones demo

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#79]
In the Settlers III Gold Edition, there exist grafics files with the following naming schemes:
* `XX.7c003e01f.dat`
* `XX.f8007e01f.dat`

In the Settlers III Amazones Demo however, only the `XX.f8007e01f.dat` scheme is present. 

As the game checks for the existens of the file `siedler3_00.7c003e01f.dat`, the grafics files of the demo cannot be used.

**Comment by nevson** [comment]
When loading the gfx files with the `XX.f8007e01f.dat` scheme I get the following errors

```bash
java.io.IOException: IO error: expected to read 124 but got 0
	at jsettlers.graphics.reader.bytereader.ByteReader.assumeToRead(ByteReader.java:176)
	at jsettlers.graphics.reader.AdvancedDatFileReader.readSequenceIndexStarts(AdvancedDatFileReader.java:322)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initFromReader(AdvancedDatFileReader.java:307)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initialize(AdvancedDatFileReader.java:259)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initializeIfNeeded(AdvancedDatFileReader.java:416)
	at jsettlers.graphics.reader.AdvancedDatFileReader.getReaderForLandscape(AdvancedDatFileReader.java:540)
	at jsettlers.graphics.map.draw.Background.addTextures(Background.java:977)
	at jsettlers.graphics.map.draw.Background.getTexture(Background.java:874)
	at jsettlers.graphics.map.draw.Background.preloadTexture(Background.java:884)
	at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:24)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "image preloader" java.lang.ArrayIndexOutOfBoundsException: 0
	at jsettlers.graphics.reader.AdvancedDatFileReader.getReaderForLandscape(AdvancedDatFileReader.java:541)
	at jsettlers.graphics.map.draw.Background.addTextures(Background.java:977)
	at jsettlers.graphics.map.draw.Background.getTexture(Background.java:874)
	at jsettlers.graphics.map.draw.Background.preloadTexture(Background.java:884)
	at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:24)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: IO error: expected to read 124 but got 0
	at jsettlers.graphics.reader.bytereader.ByteReader.assumeToRead(ByteReader.java:176)
	at jsettlers.graphics.reader.AdvancedDatFileReader.readSequenceIndexStarts(AdvancedDatFileReader.java:322)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initFromReader(AdvancedDatFileReader.java:307)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initialize(AdvancedDatFileReader.java:259)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initializeIfNeeded(AdvancedDatFileReader.java:416)
	at jsettlers.graphics.reader.AdvancedDatFileReader.access$0(AdvancedDatFileReader.java:414)
	at jsettlers.graphics.reader.AdvancedDatFileReader$GuiImageSequence.getImageSafe(AdvancedDatFileReader.java:582)
	at jsettlers.graphics.reader.AdvancedDatFileReader$GuiImageSequence.getImageSafe(AdvancedDatFileReader.java:1)
	at jsettlers.graphics.map.draw.ImageProvider.getGuiImage(ImageProvider.java:267)
	at jsettlers.graphics.map.draw.ImageProvider.getSequencedImage(ImageProvider.java:220)
	at jsettlers.graphics.map.draw.ImageProvider.getDetailedImage(ImageProvider.java:192)
	at jsettlers.graphics.map.draw.ImageProvider.getImage(ImageProvider.java:180)
	at jsettlers.graphics.utils.UIPanel.drawBackground(UIPanel.java:109)
	at jsettlers.graphics.startscreen.StartScreen.drawBackground(StartScreen.java:126)
	at jsettlers.graphics.utils.UIPanel.drawAt(UIPanel.java:93)
	at jsettlers.graphics.JSettlersScreen$PanelRegionContent.drawContent(JSettlersScreen.java:114)
	at go.graphics.region.Region.drawRegion(Region.java:109)
	at go.graphics.area.Area.drawRegionAt(Area.java:132)
	at go.graphics.area.Area.drawArea(Area.java:120)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:163)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:96)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1421)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1435)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:526)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:580)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4957)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.io.IOException: IO error: expected to read 124 but got 0
	at jsettlers.graphics.reader.bytereader.ByteReader.assumeToRead(ByteReader.java:176)
	at jsettlers.graphics.reader.AdvancedDatFileReader.readSequenceIndexStarts(AdvancedDatFileReader.java:322)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initFromReader(AdvancedDatFileReader.java:307)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initialize(AdvancedDatFileReader.java:259)
	at jsettlers.graphics.reader.AdvancedDatFileReader.initializeIfNeeded(AdvancedDatFileReader.java:416)
	at jsettlers.graphics.reader.AdvancedDatFileReader.access$0(AdvancedDatFileReader.java:414)
	at jsettlers.graphics.reader.AdvancedDatFileReader$GuiImageSequence.getImageSafe(AdvancedDatFileReader.java:582)
	at jsettlers.graphics.reader.AdvancedDatFileReader$GuiImageSequence.getImageSafe(AdvancedDatFileReader.java:1)
	at jsettlers.graphics.map.draw.ImageProvider.getGuiImage(ImageProvider.java:267)
	at jsettlers.graphics.map.draw.ImageProvider.getSequencedImage(ImageProvider.java:220)
	at jsettlers.graphics.map.draw.ImageProvider.getDetailedImage(ImageProvider.java:192)
	at jsettlers.graphics.map.draw.ImageProvider.getImage(ImageProvider.java:180)
	at jsettlers.graphics.utils.UIPanel.drawBackground(UIPanel.java:109)
	at jsettlers.graphics.utils.UIPanel.drawAt(UIPanel.java:93)
	at jsettlers.graphics.map.controls.original.panel.content.UILabeledButton.drawAt(UILabeledButton.java:48)
	at jsettlers.graphics.utils.UIPanel$ChildLink.drawAt(UIPanel.java:158)
	at jsettlers.graphics.utils.UIPanel.drawAt(UIPanel.java:99)
	at jsettlers.graphics.JSettlersScreen$PanelRegionContent.drawContent(JSettlersScreen.java:114)
	at go.graphics.region.Region.drawRegion(Region.java:109)
	at go.graphics.area.Area.drawRegionAt(Area.java:132)
	at go.graphics.area.Area.drawArea(Area.java:120)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:163)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:96)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1421)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1435)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:526)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:580)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4957)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by michaelzangl** [comment]
Now guess why that other file is required ;-).

We currently can only parse the 7c003e01f.dat files.

**Comment by michaelzangl** [comment]
Added the ability to (automatically) use the other dat files in b33508b90d7180834f874496682e16ac24d3834d
