### ISSUE TITLE
Can't click anything on OSX (Retina Display)

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#92]
OS: OSX 10.10.3 (Retina Display)
JSettlers Version: 4399793
Java Version: 1.8.0_45
Logfiles: no log dir was created in resources dir
Issue:
When I open JSettlers.jar I can see the Main Screen. When I click at "neues Einzelspeil" button, any other button or anywhere in the Main Screen then the "Netzwerkspiel beitreten" Button is displayed as pressed and nothing happens anymore.

![bildschirmfoto 2015-06-03 um 20 12 16](https://cloud.githubusercontent.com/assets/6422616/7967817/f56874ec-0a2c-11e5-917d-b91b4c0ebb28.png)

**Comment by codingberlin** [comment]
When I run Settlers.Jar in Terminal I get the following output (I clicked at "neues Einzelspiel" as described in the issue)

```
$ java -jar JSettlers.jar 
Warning: Could not find localization/labels_de_DE.properties. Falling back to next file.
Loading Sequence number 28
jsettlers.network.infrastructure.channel.socket.SocketConnectException: java.net.ConnectException: Connection refused
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:23)
	at jsettlers.network.infrastructure.channel.Channel.<init>(Channel.java:66)
	at jsettlers.network.infrastructure.channel.AsyncChannel.<init>(AsyncChannel.java:22)
	at jsettlers.network.client.NetworkClient.<init>(NetworkClient.java:68)
	at jsettlers.main.AsyncNetworkClientConnector$1.run(AsyncNetworkClientConnector.java:30)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jsettlers.network.infrastructure.channel.socket.standard.JavaSocketFactory.generateSocket(JavaSocketFactory.java:21)
	... 4 more

**Comment by codingberlin** [comment]
Same console output with
```
$ java -jar JSettlers.jar --console-output

**Comment by codingberlin** [comment]
I checked out the code and debugged it.
The calculation of the click position of the mouse needs to be adopted for Retina displays.

**Comment by codingberlin** [comment]
Found out that in the class GOSwingEventConverter a factor of 2 would fix the problem on my machine (for the start screen and in-game - where I noticed the problem, too):
```
	private UIPoint convertToLocal(MouseEvent e) {
		return new UIPoint(e.getX() * 2, (e.getComponent().getHeight() - e.getY()) * 2);
	}
```
Unfortunately I guess it would break all other non Retina displays.
I don't know how to detect if the factor is needed or if another factor is needed in future when even more sharper displays are invented.

Any ideas?

**Comment by namelessjames** [comment]
Maybe something like that will work:
```
public static boolean hasRetinaDisplay() {
  Object obj = Toolkit.getDefaultToolkit()
      .getDesktopProperty(
          "apple.awt.contentScaleFactor");
  if (obj instanceof Float) {
    Float f = (Float) obj;
    int scale = f.intValue();
    return (scale == 2); // 1 indicates a regular mac display.
  }
  return false;
}
```
http://stackoverflow.com/questions/20767708/how-do-you-detect-a-retina-display-in-java

**Comment by codingberlin** [comment]
@namelessjames thanks for the link. This was a good starting point.
I figured out that I need some additional code to cover usage of multiple monitors when one is retina and another is not and you move the JFrame around.

I just forked the repo and will investigate some more effort soon and then send a pull request.

**Comment by codingberlin** [comment]
See #93

**Comment by michaelzangl** [comment]
#93 is merged
